
```{r}
library(tidyverse)
library(readr)
library(here)

library(ggsoccer)

library(fmesher)
library(sf)
library(inlabru)
library(INLA)
```

# Data

```{r}
pitch_length <- 105
pitch_width <- 68

dataset <- read_csv(here("data", "dataset.csv"))
dataset_sf <- dataset %>% st_as_sf(coords = c("x", "y"), crs = NA)
```

```{r}
# T MESH (1D Temporal)
interval <- 5
pred_interval <- 10

t_range <- range(dataset_sf$time_sec, na.rm = TRUE)
t_start <- floor(t_range[1] / interval) * interval
t_end   <- ceiling(t_range[2] / interval) * interval + pred_interval

tknots  <- seq(from = t_start, to = t_end, by = interval)
mesh_t  <- fm_mesh_1d(tknots)

# S MESH (2D Spatial)
pitch_x = c(0, pitch_length)
pitch_y = c(0, pitch_width)

pitch_poly <- st_as_sfc(st_bbox(c(
  xmin = pitch_x[1], xmax = pitch_x[2], 
  ymin = pitch_y[1], ymax = pitch_y[2]
)))

boundary <- fm_as_segm(pitch_poly)

mesh_s <- fm_mesh_2d_inla(
  boundary = boundary,
  max.edge = c(3, 12),
  offset   = c(5, 15),
  cutoff   = 2
)
```

```{r}
range(dataset_sf$time_sec, na.rm = TRUE)

mesh_t$loc
```

```{r}
plot(mesh_s)
```
# Model

```{r}
spde <- inla.spde2.pcmatern(
  mesh = mesh_s,
  prior.sigma = c(0.1, 0.01),
  prior.range = c(10, 0.01)
)
```

```{r}
cmp <- ~ Intercept(1) +
  field(
    geometry,
    model = spde,
    group = time_sec,
    group_mapper = bru_mapper(mesh_t, indexed = TRUE),
    control.group = list(
      model = "ar1",
      hyper = list(
        rho = list(
          prior = "pc.cor1",
          param = c(0.7, 0.9) 
        )
      )
    )
  )
```


```{r}
ips <- fm_int(
    domain = list(geometry = mesh_s, time_sec = mesh_t),
    samplers = list(geometry = pitch_poly)
  )

fit <- bru(
  cmp,
  bru_obs(
    geometry + time_sec ~ .,
    family = "cp",
    data = dataset_sf,
    ips = ips
  )
)
```

```{r}
summary(fit)
```

```{r}
intercept_exp <- INLA::inla.tmarginal(exp, fit$marginals.fixed$Intercept)
plot(intercept_exp, type = "l", main = "Intersity (exp)")
plot(fit$marginals.hyperpar$`Range for field`, type = "l", main = "Range")
plot(fit$marginals.hyperpar$`Stdev for field`, type = "l", main = "StDev")
plot(fit$marginals.hyperpar$`GroupRho for field`, type = "l", main = "ACF1")
```

```{r}
ppxl <- fm_pixels(mesh_s, mask = pitch_poly, format = "sf")
ppxl_all <- fm_cprod(ppxl, data.frame(time_sec = c(0, 10, 20, 30, 31:40)))

n_players <- 22
pixel_area <- 7140 / nrow(ppxl) 

samples <- generate(
  fit, 
  ppxl_all, 
  ~ exp(field)
)

df_samples <- cbind(as.data.frame(ppxl_all), as.data.frame(samples))
lambda_conditional <- df_samples %>%
  pivot_longer(
    cols = starts_with("V"), 
    names_to = "sample_id", 
    values_to = "unnormalized_intensity"
  ) %>% 
  group_by(time_sec, sample_id) %>%
  mutate(
    spatial_integral = sum(unnormalized_intensity * pixel_area),
    conditional_intensity = n_players * (unnormalized_intensity / spatial_integral)
  ) %>%
  ungroup() %>% 
  group_by(geometry, time_sec) %>%
  summarize(
    mean = mean(conditional_intensity),
    sd = sd(conditional_intensity),
    q025 = quantile(conditional_intensity, 0.025),
    q975 = quantile(conditional_intensity, 0.975),
    .groups = "drop"
  ) %>%
  st_as_sf()
```

```{r}
ggplot() +
  gg(lambda_conditional, geom = "tile", aes(fill = mean)) +
  facet_wrap(~time_sec) +
  coord_sf() + 
  annotate_pitch(
    dimensions = pitch_international,
    fill       = NA,
    colour     = "white",
    alpha      = 0.3
  ) +
  scale_fill_viridis_c(option = "magma") 
```

