```{r}
library(tidyverse)
library(here)
library(readr)

library(INLA)
library(inlabru)
library(fmesher)
library(sp)
library(sf)

source(here('src', 'modeling.R'))
source(here('src', 'metrics.R'))
```

# Data

```{r}
events <- read_csv(here('data', 'processed', 'events.csv')) %>% 
  distinct() %>% 
  rename(team_with_poss = team_id)

tracking <- read_csv(here('data', 'processed', 'tracking.csv')) %>%
  distinct() %>% 
  rename(period = period_id)

ball <- tracking %>% 
  filter(player_id == 'ball') %>% 
  select(period, time_sec_orig, x_ball = x_pitch, y_ball = y_pitch, match_id)

pitch_length <- 105
pitch_width <- 68
```

```{r}
event_type = "SHOT"
event_subtype = NA
start_time = 30
end_time = 0
pred_time_event = 0

dataset <- prepare_data(events, tracking, event_type, event_subtype, start_time, end_time, pred_time_event, keep_all_teams = TRUE)

# Filter for Fortuna Düsseldorf (DFL-CLU-00000P)
fortuna_id <- "DFL-CLU-00000P"

# Identify events where Fortuna is attacking
fortuna_attack_events <- dataset %>%
  filter(team_id == fortuna_id, team_code == "Attack") %>%
  pull(anchor_event_id) %>%
  unique()

# Identify events where Fortuna is defending
fortuna_defend_events <- dataset %>%
  filter(team_id == fortuna_id, team_code == "Defense") %>%
  pull(anchor_event_id) %>%
  unique()

# Create dataset for when Fortuna is attacking (includes Fortuna and opponents)
data_set_fortuna_attack <- dataset %>%
  filter(anchor_event_id %in% fortuna_attack_events)

# Create dataset for when Fortuna is defending (includes Fortuna and opponents)
data_set_fortuna_defend <- dataset %>%
  filter(anchor_event_id %in% fortuna_defend_events)

# For the rest of the script, we will use the attacking dataset as an example
dataset_fortuna <- data_set_fortuna_attack
dataset_sf <- dataset_fortuna %>% st_as_sf(coords = c("x", "y"), crs = NA)
```

# Mesh

```{r}
mesh <- create_meshes(dataset_fortuna, max.edge = c(3, 12), offset = c(5, 15), cutoff = 2)
```

```{r}
plot(mesh$s)
```

# SPDE Prior

```{r}
spde <- inla.spde2.pcmatern(
  mesh = mesh$s,
  prior.sigma = c(1, 0.01),
  prior.range = c(100, 0.99)
)
```

# FIT

```{r}
cmp <- ~ Intercept(1) +
  Common(
    geometry,
    model = spde,
    group = time_sec,
    group_mapper = bru_mapper(mesh$t, indexed=TRUE),
    control.group = list(model = "ar1")
  ) +
  Difference(
    geometry,
    model = spde,
    group = time_sec,
    group_mapper = bru_mapper(mesh$t, indexed=TRUE),
    control.group = list(model = "ar1")
  )

fml.atk <- geometry ~ Intercept + Common + Difference / 2
fml.def <- geometry ~ Intercept + Common - Difference / 2
```


```{r}
ips <- fm_int(
    domain = list(geometry = mesh$s, time_sec = mesh$t),
    samplers = list(geometry = mesh$poly)
  )

lik_atk <- bru_obs("cp",
  formula = fml.atk,
  data = dataset_sf[dataset_sf$team_code == "Attack", ],
  ips = ips
)
lik_def <- bru_obs("cp",
  formula = fml.def,
  data = dataset_sf[dataset_sf$team_code == "Defense", ],
  ips = ips
)

fit <- bru(
  cmp,
  lik_atk,
  lik_def
)
```

```{r}
summary(fit)

saveRDS(fit, here("output", "fit_fortuna.rds"))
```

```{r}
ppxl <- fm_pixels(mesh$s, mask = mesh$poly, format = "sf")
pred_grid <- fm_cprod(ppxl, data.frame(time_sec = seq(1, 30)))

# Predict Attack Intensity
pred_atk <- predict(
  fit,
  newdata = pred_grid,
  formula = ~ exp(Intercept + Common + Difference / 2)
)

# # Predict Defense Intensity
# pred_def <- predict(
#   fit,
#   newdata = pred_grid,
#   formula = ~ exp(Intercept + Common - Difference / 2)
# )
# 
# # Predict the Common spatial field
# pred_common <- predict(
#   fit,
#   newdata = pred_grid,
#   formula = ~ Common
# )

# Predict the Difference spatial field
pred_diff <- predict(
  fit,
  newdata = pred_grid,
  formula = ~ Difference
)

pred_list <- list(
  pred_atk = pred_atk,
  pred_diff = pred_diff
)
saveRDS(pred_list, here("output", "pred_fortuna.rds"))
```


# Metrics Calculation

```{r}
df_ssi <- compute_ssi(pred_diff)
saveRDS(df_ssi, here("output", "ssi_fortuna.rds"))
df_xST <- compute_xST(pred_atk)
saveRDS(df_xST, here("output", "xST_fortuna.rds"))
```

```{r}
df_ssi
df_xST
```



