```{r}
library(conflicted)
library(tidyverse)
library(here)
library(readr)
library(lmtest)
library(zoo)
library(vars)
library(fuzzyjoin)
library(tseries)

conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("lag", "dplyr")

source(here('src', 'plots.R'))
```

```{r}
events <- read_csv(here('data', 'events_dfl.csv'))
tracking <- read_csv(here('data', 'tracking_dfl_secs.csv'))
```

```{r}
goals <- events %>%
  filter(type == "SHOT", success == TRUE) %>% 
  distinct(start_time_s, match_id, team_name) %>% 
  count(match_id, team_name)

available_matches <- tracking %>% 
  distinct(match_id, team_name) %>% 
  filter(team_name != 'Ball') %>% 
  left_join(goals, by = c('match_id', 'team_name')) %>% 
  mutate(n = replace_na(n, 0))
```

```{r}
period_offsets <- tracking %>%
  group_by(match_id, period) %>%
  summarise(max_time = max(time_seg, na.rm = TRUE), .groups = "drop") %>%
  group_by(match_id) %>%
  arrange(period, .by_group = TRUE) %>%
  mutate(time_offset = lag(cumsum(max_time), default = 0)) %>%
  select(match_id, period, time_offset)

tracking <- tracking %>%
  left_join(period_offsets, by = c("match_id", "period")) %>%
  mutate(time_seg_continuous = time_seg + time_offset) %>%
  select(-time_offset)

events <- events %>% 
  left_join(period_offsets) %>% 
  mutate(time_seg_continuous = start_time_s + time_offset) %>%
  select(-time_offset)

```


```{r}
matches <- c("000001_DFL-MAT-J03WMX", "000001_DFL-MAT-J03WN1", "000002_DFL-MAT-J03WPY")

shot_df <- events %>%
  filter(type == "SHOT", subtype %in% NA) %>%
  dplyr::select(match_id, team_name, period, time_seg_continuous)

temporal_dependency <- tracking %>%
  filter(player_id != "ball", !is.na(team_name), is_goalkeeper != 1) %>%
  group_by(match_id, team_name, time_seg_continuous, period) %>%
  summarise(
    tm_mu_x = mean(x_pitch, na.rm = TRUE),
    tm_mu_y = mean(y_pitch, na.rm = TRUE),
    .groups = "drop"
  ) %>% 
  group_by(match_id) %>%
  mutate(match_label = paste(unique(team_name), collapse = " vs. ")) %>%
  ungroup()

temp_plot <- temporal_dependency %>% 
  filter(match_id %in% matches)

plt <- ggplot(temp_plot, aes(x = time_seg_continuous, y = tm_mu_x, color = team_name)) +
  geom_line(alpha = 1) +
  facet_wrap(~match_label, ncol = 1) + 
  theme_minimal(base_family = "playfair", base_size = 12) +
  theme(
    plot.background  = element_rect(fill = "white", colour = NA),
    panel.border     = element_rect(colour = "#DDDDDD", fill = NA, linewidth = 0.4),
    plot.margin = margin(24, 28, 18, 28),
    strip.background = element_rect(fill = "#F2F2F2", colour = "#DDDDDD", linewidth = 0.4),
    strip.text       = element_text(
      colour = "#111111", size = 12, face = "bold",
      margin = margin(t = 8, b = 8)
    ),
        # Top facet labels (Quantiles / Mean)
    strip.text.x = element_text(
      colour = "#111111", 
      size = 12, 
      face = "bold",
      margin = margin(t = 8, b = 8)
    ),

    # Side facet labels (Attack / Defense)
    strip.text.y = element_text(
      colour = "#111111", 
      size = 16,           # Increased size for the side text
      face = "bold",
      margin = margin(l = 8, r = 8) # Use left/right margin for vertical text padding
    )
  ) +
  labs(
    x = "Time (sec)",
    y = "Average X-Pitch Position",
    color = "Team"
  )

plt
ggsave(
  filename = here('output', 'img', "granger", "time_series.pdf"),
  plot = plt,
  width = 14,      # Standard width
  height = 8,    # Give it lots of vertical room for those 6+ rows!
  dpi = 300       # High resolution
)
```


# ALL GAME

```{r}
run_granger_stationary <- function(df, lag_order = 5) {
  if (nrow(df) <= lag_order) return(NULL) 
  
  g_1_to_2 <- grangertest(vel_x_Team_2 ~ vel_x_Team_1, order = lag_order, data = df)
  g_2_to_1 <- grangertest(vel_x_Team_1 ~ vel_x_Team_2, order = lag_order, data = df)
  
  tibble(
    causality_direction = c("Team_1 -> Team_2", "Team_2 -> Team_1"),
    f_stat = c(g_1_to_2$F[2], g_2_to_1$F[2]),
    p_value = c(g_1_to_2$`Pr(>F)`[2], g_2_to_1$`Pr(>F)`[2])
  )
}

get_adf_pvalue <- function(x) {
  test <- adf.test(x, alternative = "stationary")
  print(test)
  return(test$p.value)
}
```


```{r}
ts <- temporal_dependency %>%
  group_by(match_id) %>%
  mutate(team_label = paste0("Team_", dense_rank(team_name))) %>%
  pivot_wider(
    id_cols = c(match_id, period, time_seg_continuous),
    names_from = team_label,
    values_from = c(tm_mu_x, tm_mu_y)
  ) %>%
  arrange(match_id, period, time_seg_continuous) %>%
  group_by(match_id, period) %>%
  mutate(
    vel_x_Team_1 = tm_mu_x_Team_1 - lag(tm_mu_x_Team_1),
    vel_x_Team_2 = tm_mu_x_Team_2 - lag(tm_mu_x_Team_2)
  ) %>%
  ungroup()
```


```{r}
stationarity_results <- ts %>%
  group_by(match_id) %>%
  summarise(
    p_val_pos_Team_1 = get_adf_pvalue(tm_mu_x_Team_1),
    p_val_pos_Team_2 = get_adf_pvalue(tm_mu_x_Team_2),
    .groups = "drop"
  ) %>%
  mutate(
    is_stat_pos_Team_1 = p_val_pos_Team_1 < 0.05,
    is_stat_pos_Team_2 = p_val_pos_Team_2 < 0.05,
  )

print(stationarity_results)

granger_global <- ts %>%
  group_by(match_id) %>%
  reframe(run_granger_stationary(pick(everything()), lag_order = 5)) %>% 
  mutate(h0_rej = if_else(p_value <= 0.05, TRUE, FALSE))

print(granger_global)
# p-values < 0.05 indicate the left series "causes" (anticipates) the right series.
```

# SHOTS VS RANDOM MOMENTS

```{r}
build_up_window <- 30 

shot_intervals <- shot_df %>%
  distinct() %>% 
  transmute(
    match_id, 
    period, 
    shot_time = time_seg_continuous,
    window_start = shot_time - build_up_window,
    window_end = shot_time,
    window_id = paste0("Shot_", match_id, "_", shot_time) # Unique ID per event
  )

ts_shots <- ts %>%
  inner_join(
    shot_intervals,
    by = join_by(match_id, period, between(time_seg_continuous, window_start, window_end))
  ) %>%
  mutate(contexto_jogo = "Shot Moment")
```

```{r}
set.seed(52)
random_intervals <- ts %>%
  anti_join(
    shot_intervals,
    by = join_by(match_id, period, between(time_seg_continuous, window_start, window_end))
  ) %>%
  group_by(match_id) %>%
  filter(time_seg_continuous >= min(time_seg_continuous) + build_up_window) %>%
  slice_sample(n = 50) %>% 
  ungroup() %>%
  transmute(
    match_id, 
    period,
    window_start = time_seg_continuous - build_up_window,
    window_end = time_seg_continuous,
    window_id = paste0("Random_", match_id, "_", row_number())
  )

ts_random <- ts %>%
  inner_join(
    random_intervals,
    by = join_by(match_id, period, between(time_seg_continuous, window_start, window_end))
  ) %>%
  mutate(contexto_jogo = "Fluxo Normal")
```


```{r}
granger_shot <- bind_rows(ts_shots, ts_random) %>%
  group_by(match_id, contexto_jogo, window_id) %>%
  reframe(
    run_granger_stationary(pick(everything()), lag_order = 5)
  ) %>%
  arrange(match_id, contexto_jogo, causality_direction) %>% 
  mutate(p_95 = p_value < 0.05)
```

```{r}
granger_shot %>%
  group_by(contexto_jogo, causality_direction) %>%
  summarise(
    count = n(),
    significant = sum(p_95),
    perc = (sum(p_95) / n()) * 100
  ) %>%
  arrange(desc(perc))
```
```{r}
successes <- sum(granger_shot$p_95, na.rm = TRUE)
trials <- nrow(granger_shot) 
binom_result <- binom.test(x = successes, n = trials, p = 0.05, alternative = "greater")

print(binom_result)
```
```{r}
fluxo_normal <- c(177, 420 - 177) # [Significativos, Não-Significativos]
momento_gol  <- c(32, 342 - 32)   # [Significativos, Não-Significativos]

tabela_contingencia <- rbind(fluxo_normal, momento_gol)
colnames(tabela_contingencia) <- c("Significativo", "Nao_Significativo")
rownames(tabela_contingencia) <- c("Fluxo Normal", "Momento do Gol")

resultado_teste <- chisq.test(tabela_contingencia)
print(resultado_teste)
```
```{r}
wilcox.test(p_value ~ contexto_jogo, data = granger_shot)
wilcox.test(f_stat ~ contexto_jogo, data = granger_shot)
```

```{r}
ggplot(granger_shot, aes(x = contexto_jogo, y = p_value, fill = contexto_jogo)) +
  geom_boxplot() +
  labs(title = "Distribuição de P-valores: Chute vs Fluxo Normal",
       y = "P-valor", x = "Contexto") +
  theme_minimal()
```


